[versions]
groupId = "de.jensklingenberg.scrako"
vannikMavenPublish = "0.28.0"
coreVersion = "0.8.3"
[plugins]
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vannikMavenPublish" }
